# Generated by Django 3.0.6 on 2020-05-21 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residential_address1', models.TextField(blank=True, null=True)),
                ('residential_address2', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_company', models.BooleanField(default=False)),
                ('is_firm', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('firm_name', models.CharField(blank=True, max_length=30, null=True)),
                ('person_name', models.CharField(blank=True, max_length=30, null=True)),
                ('person_relation', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdentityDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('ssn', models.CharField(blank=True, max_length=15, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=15, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=15, null=True)),
                ('dependents', models.CharField(blank=True, max_length=5, null=True)),
                ('investment_experience', models.CharField(blank=True, max_length=30, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('basic_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.BasicDetails')),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.IdentityDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
