# Generated by Django 3.0.6 on 2020-05-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200526_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.CharField(default='test', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
