# Generated by Django 3.0.6 on 2020-05-28 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20200526_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='password',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
