# Generated by Django 3.0.6 on 2020-06-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200528_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('symbol', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
