# Generated by Django 3.0.6 on 2020-06-12 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_stocknames'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydetails',
            name='aadharcard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identitydetails',
            name='accountno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identitydetails',
            name='buyingpower',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identitydetails',
            name='pancard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identitydetails',
            name='portfolio_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('stockticker', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('order', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, choices=[('pending', 'pending'), ('executed', 'executed')], default='pending', null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_rel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.TextField(blank=True, null=True)),
                ('ticker', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('ordertype', models.TextField(blank=True, null=True)),
                ('unrealised_gainloss', models.TextField(blank=True, null=True)),
                ('margin', models.TextField(blank=True, null=True)),
                ('interest', models.TextField(blank=True, null=True)),
                ('equity', models.TextField(blank=True, null=True)),
                ('stockname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockposition_rel', to='accounts.StockNames')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userposition_rel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portolfio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.TextField(blank=True, null=True)),
                ('tensector', models.TextField(blank=True, null=True)),
                ('gainloss', models.TextField(blank=True, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_rel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
