# Generated by Django 3.0.6 on 2020-06-12 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200612_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 12, 22, 14, 4, 229713), null=True),
        ),
    ]
