# Generated by Django 3.0.6 on 2020-06-15 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200614_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='market_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='price_to_book',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='trailing_pe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='accountno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='equity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='interest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='margin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='ordertype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='ticker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='unrealised_gainloss',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 15, 9, 45, 25, 584835), null=True),
        ),
    ]
