# Generated by Django 3.0.6 on 2020-06-15 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200615_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 15, 9, 53, 25, 921836), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 15, 9, 53, 25, 920995), null=True),
        ),
    ]
