# Generated by Django 3.0.6 on 2020-06-17 07:28

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200617_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='position',
            name='price_to_book',
        ),
        migrations.RemoveField(
            model_name='position',
            name='trailing_pe',
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 17, 12, 58, 40, 960048), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 17, 12, 58, 40, 959561), null=True),
        ),
        migrations.CreateModel(
            name='StockGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailing_pe', models.FloatField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('price_to_book', models.FloatField(blank=True, null=True)),
                ('company_info', models.TextField(blank=True, null=True)),
                ('officers', django.contrib.postgres.fields.jsonb.JSONField()),
                ('employees', models.CharField(blank=True, max_length=50, null=True)),
                ('headquaters', models.CharField(blank=True, max_length=50, null=True)),
                ('pe_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('open_price', models.CharField(blank=True, max_length=50, null=True)),
                ('low_today', models.CharField(blank=True, max_length=50, null=True)),
                ('high_today', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general', to='accounts.StockNames')),
            ],
        ),
    ]
