# Generated by Django 3.0.6 on 2020-06-17 08:26

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200617_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 17, 13, 56, 0, 95750), null=True),
        ),
        migrations.AlterField(
            model_name='stockgeneral',
            name='officers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 17, 13, 56, 0, 95063), null=True),
        ),
    ]
