# Generated by Django 3.0.6 on 2020-06-17 15:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200617_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 17, 21, 28, 57, 901804), null=True),
        ),
        migrations.AlterField(
            model_name='stockgeneral',
            name='stock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general', to='accounts.StockNames'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 17, 21, 28, 57, 901216), null=True),
        ),
    ]
