# Generated by Django 3.0.6 on 2020-06-19 07:24

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200617_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockgeneral',
            old_name='employees',
            new_name='DE',
        ),
        migrations.RenameField(
            model_name='stockgeneral',
            old_name='headquaters',
            new_name='GISC',
        ),
        migrations.RenameField(
            model_name='stockgeneral',
            old_name='high_today',
            new_name='GPM',
        ),
        migrations.RenameField(
            model_name='stockgeneral',
            old_name='low_today',
            new_name='Industry',
        ),
        migrations.RenameField(
            model_name='stockgeneral',
            old_name='open_price',
            new_name='PE',
        ),
        migrations.RenameField(
            model_name='stockgeneral',
            old_name='pe_ratio',
            new_name='ROE',
        ),
        migrations.RenameField(
            model_name='stockgeneral',
            old_name='stock',
            new_name='Stockticker',
        ),
        migrations.RemoveField(
            model_name='stockgeneral',
            name='company_info',
        ),
        migrations.RemoveField(
            model_name='stockgeneral',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='stockgeneral',
            name='officers',
        ),
        migrations.RemoveField(
            model_name='stockgeneral',
            name='price_to_book',
        ),
        migrations.RemoveField(
            model_name='stockgeneral',
            name='trailing_pe',
        ),
        migrations.AddField(
            model_name='stockgeneral',
            name='companyname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 19, 12, 54, 9, 588445), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 19, 12, 54, 9, 587516), null=True),
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailing_pe', models.FloatField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('price_to_book', models.FloatField(blank=True, null=True)),
                ('company_info', models.TextField(blank=True, null=True)),
                ('officers', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('employees', models.CharField(blank=True, max_length=500, null=True)),
                ('headquaters', models.CharField(blank=True, max_length=500, null=True)),
                ('pe_ratio', models.CharField(blank=True, max_length=500, null=True)),
                ('open_price', models.CharField(blank=True, max_length=500, null=True)),
                ('low_today', models.CharField(blank=True, max_length=500, null=True)),
                ('high_today', models.CharField(blank=True, max_length=500, null=True)),
                ('stock', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_info', to='accounts.StockNames')),
            ],
        ),
    ]
