# Generated by Django 3.0.6 on 2020-06-20 03:58

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200619_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='current_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 20, 9, 28, 20, 375741), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 20, 9, 28, 20, 374741), null=True),
        ),
    ]
