# Generated by Django 3.0.6 on 2020-06-30 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200620_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 11, 0, 20, 639635), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 11, 0, 20, 639029), null=True),
        ),
    ]
