# Generated by Django 3.0.6 on 2020-06-30 08:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200630_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='order',
            new_name='ordertype',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='limit_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 13, 37, 16, 415876), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stockticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transaction_rel', to='accounts.StockNames'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 13, 37, 16, 415242), null=True),
        ),
    ]
