# Generated by Django 3.0.6 on 2020-07-16 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200706_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expires',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 16, 23, 27, 40, 180637), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 16, 23, 27, 40, 179185), null=True),
        ),
    ]
