# Generated by Django 3.0.6 on 2020-07-13 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200706_1129'),
    ]

    operations = [

        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 15, 21, 51, 411342), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 15, 21, 51, 410703), null=True),
        ),
    ]
