# Generated by Django 3.0.6 on 2020-07-13 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20200713_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 18, 38, 57, 307930), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 18, 38, 57, 307069), null=True),
        ),
    ]
