# Generated by Django 3.0.6 on 2020-07-14 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20200713_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remove_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 14, 21, 31, 11, 31452), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 14, 21, 31, 11, 30810), null=True),
        ),
    ]
