# Generated by Django 3.0.6 on 2020-07-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20200714_2131'),
        ('accounts', '0027_auto_20200716_2327'),
    ]

    operations = [
    ]
