# Generated by Django 3.0.6 on 2020-07-22 07:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20200722_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='transaction_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockposition_transaction_rel', to='accounts.Transaction'),
        ),

        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 22, 13, 2, 18, 14919), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 22, 13, 2, 18, 14170), null=True),
        ),
    ]
