# Generated by Django 3.0.6 on 2020-07-31 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20200728_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='sector',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),

        migrations.AlterField(
            model_name='position',
            name='unrealised_gainloss',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 31, 13, 1, 35, 377114), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 31, 13, 1, 35, 376451), null=True),
        ),
    ]
