# Generated by Django 3.0.6 on 2020-08-11 07:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0034_auto_20200731_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 11, 13, 8, 20, 889976), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 11, 13, 8, 20, 889301), null=True),
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_number', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 11, 13, 8, 20, 891150), null=True)),
                ('position_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histroy_position_rel', to='accounts.Position')),
            ],
        ),
        migrations.CreateModel(
            name='TotalGainLoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gainloss', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 11, 13, 8, 20, 891484), null=True)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_total_gl_rel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GainLossHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unrealised_gainloss', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('realised_gainloss', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('total_cash', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 11, 13, 8, 20, 891923), null=True)),
                ('position_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_history_position_rel', to='accounts.Position')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_gl_history_rel', to='accounts.StockNames')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_gl_history_rel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
