# Generated by Django 3.0.6 on 2020-08-14 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20200814_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='gainlosshistory',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gainlosshistory',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 14, 20, 20, 49, 845615), null=True),
        ),
        migrations.AlterField(
            model_name='identitydetails',
            name='buyingpower',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 14, 20, 20, 49, 843768), null=True),
        ),
        migrations.AlterField(
            model_name='totalgainloss',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 14, 20, 20, 49, 845165), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 14, 20, 20, 49, 843114), null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 14, 20, 20, 49, 844825), null=True),
        ),
    ]
